@host=http://localhost:3000/v1

//ITEM
### tous les articles
GET {{host}}/items
### 1 article en fonction de son id
GET {{host}}/items/18
### les articles pour une catégorie
GET {{host}}/items/category/3
### les articles pour une marque
GET {{host}}/items/brand/5
### les articles pour un rayon
GET {{host}}/items/shelf/2

//BRAND
### toutes les marques
GET {{host}}/brands
### 1 marque en fonction de son id
GET {{host}}/brands/2