@host=process.env.BASE_URL:3000/api

//ITEM
### tous les articles
GET {{host}}/items
### 1 article en fonction de son id
GET {{host}}/items/6

//ITEMS FILTER
### filtre sur les 3 entrées : brand, category et shelf
GET {{host}}/items/filter?shelf=Epicerie sucrée&category=Friandises&brand=Lindt
### filtre sur 2 entrées : category et shelf
GET {{host}}/items/filter?shelf=Animalerie&category=Animaux
### filtre sur une seule entrée
GET {{host}}/items/filter?shelf=Frais

//CATEGORY
### liste des catégories
GET {{host}}/categories
### 1 catégorie en fonction de son id
GET {{host}}/categories/6

//SHELF
### liste des rayons
GET {{host}}/shelves
### 1 rayon en fonction de son id
GET {{host}}/shelves/6

//BRAND
### liste des marques
GET {{host}}/brands
### 1 marque en fonction de son id
GET {{host}}/brands/2